### ISSUE TITLE
🛠 Tooling: Create a common component for code tags

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [JoshuaKGoldberg/emoji-blast#291]
### Bug Report Checklist

- [X] I have tried restarting my IDE and the issue persists.
- [X] I have pulled the latest `main` branch of the repository.
- [X] I have [searched for related issues](https://github.com/JoshuaKGoldberg/emoji-blast/issues?q=is%3Aissue) and found none that matched my issue.

### Overview

This comment exists in `doc-content.tsx`:

> ```ts
> // TODO: create a component for code tag so that the styles are automatically applied
> ```

It's in reference to there being a lot of `<code css={usageStyles.code}>` tags in the page. Agreed, this would be a nice opportunity to refactor a bit to extract out a shared component for code.

**Comment by Princeyadav05** [comment]
@JoshuaKGoldberg has done the required changes and ran the site locally, everything worked fine. 
Let me know if anything needs to be changed here.
