### ISSUE TITLE
🚀 Feature: Group demo examples by type

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [JoshuaKGoldberg/emoji-blast#292]
### Bug Report Checklist

- [X] I have pulled the latest `main` branch of the repository.
- [X] I have [searched for related issues](https://github.com/JoshuaKGoldberg/emoji-blast/issues?q=is%3Aissue) and found none that matched my issue.

### Overview

This comment exists in `side-bar.tsx`:

> ```ts
> // TODO: separate the examples into different tabs by type
> ```

Agreed, that'd be nice. It's a _big_ scrolling list right now.

**Comment by Princeyadav05** [comment]
Hi @JoshuaKGoldberg, would love your help here with styling and what kind of look you want to go for.
I've tried to add basic buttons without much styling.

<img width="1678" alt="image" src="https://github.com/JoshuaKGoldberg/emoji-blast/assets/22894003/1b998f7e-a95e-4a34-802d-fad77b9def4b">
<img width="1678" alt="image" src="https://github.com/JoshuaKGoldberg/emoji-blast/assets/22894003/2393ef4b-8160-4227-a397-33f0e53694b7">

What exactly do you have in mind. Are these buttons okay and I should make then in center. what kind of look do you want to go for? Like the header links?

I also tried to use the basic buttons and style them a bit.

<img width="1678" alt="image" src="https://github.com/JoshuaKGoldberg/emoji-blast/assets/22894003/a004bd3b-94f1-4328-bad5-dc9889a9efde">

Do let me know what you have in mind.

**Comment by JoshuaKGoldberg** [comment]
👋 @Princeyadav05, thanks for looking at this! I like the way the tabs look - let's try for that? Note that it should be usable in mobile view and be accessible. Folks should still be able to use it with only a keyboard, and it should have proper HTML semantics for tabs.

I should also note that #405 -> #406 are also happening. I can help with merge conflicts if #406 ends up getting merged before your PR here.

**Comment by JoshuaKGoldberg** [comment]
Fixed by #406.
