### ISSUE TITLE
🐛 Bug: when activated with the keyboard, emojis on the site originate from top left corner

### ISSUE THREAD

**Issue by brawaru** [JoshuaKGoldberg/emoji-blast#315]
### Bug Report Checklist

- [X] I have tried restarting my IDE and the issue persists.
- [X] I have pulled the latest `main` branch of the repository.
- [X] I have [searched for related issues](https://github.com/JoshuaKGoldberg/emoji-blast/issues?q=is%3Aissue) and found none that matched my issue.

### Expected

When I press the **Click Me** button with the keyboard, I'd expect emojis blast from the button's position (prolly centre of the button) 🤩💥💥

<p align="center">
<img src="https://github.com/JoshuaKGoldberg/emoji-blast/assets/10401817/69a9d750-0cfc-44ed-a771-91d0c33052ca" alt="Screenshot of the blast originating from the button's position">
</p>

### Actual

Emojis blast from the top left corner of the page and this ain't so exciting when most of them end up beyond the visible area 😔⛈️

<p align="center">
<img src="https://github.com/JoshuaKGoldberg/emoji-blast/assets/10401817/d062139f-6cfe-4b05-b2ed-551c070af695" alt="Emojis are barely visible as they appear from the top left corner of the viewport">
</p>

### Additional Info

<details><summary>Lies, lies everywhere 😡</summary>
<p>

The first two checkboxes in checklist aren't applicable but they're required: I didn't pull the repo, nor opened IDE 😏🐸

</p>
</details>

**Comment by JoshuaKGoldberg** [comment]
Ha, nice catch! Thanks for reporting. I honestly just threw that button together quickly last minute.

https://github.com/JoshuaKGoldberg/emoji-blast/blob/43e280beb46fb1b3f684ef180d9190fd10688c1c/packages/emoji-blast-site/src/components/hero/hero.tsx#L29-L34

I think a good fix would be that if the event doesn't have `clientX` and `clientY`, then to not pass a `position` at all. That way the blast will default to some random position on the page.

A probably-better alternative would be to have the emoji blast originate from the element itself. That might be a bit more work? The _Title Explosion_ demo makes me think it's a bit more work.

Either way I'm happy for a PR!

**Comment by JoshuaKGoldberg** [comment]
Haha, shoutout @danielroe for reminding me of [`getBoundingClientRect()`](https://developer.mozilla.org/en-US/docs/Web/API/Element/getBoundingClientRect). Let's use that as a default if the event doesn't have coordinates.
